version: '3.4'

services:
  webappkey:
    image: ${DOCKER_REGISTRY-}webappkey
    build:
      context: .
      dockerfile: WebAppKey/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production



